apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azurelustre.serviceAccountNameController" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azurelustre.labels" . | nindent 4 }}
  {{- if eq .Values.IsWorkloadIdentityEnabled "Enabled" }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.IdentityClientId | quote }}
    {{- if .Values.IdentityTenantId }}
    azure.workload.identity/tenant-id: {{ .Values.IdentityTenantId | quote }}
    {{- end }}
  {{- end }}
{{- include "azurelustre.imagePullSecrets" . }}
