{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "azurelustre.fullname" . }}-node-status-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azurelustre.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "azurelustre.serviceAccountNameNode" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "azurelustre.fullname" . }}-node-status-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
