apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azurelustre.serviceAccountNameNode" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azurelustre.labels" . | nindent 4 }}
{{- include "azurelustre.imagePullSecrets" . }}
