---
version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - gosmopolitan
    - grouper
    - inamedparam
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testifylint
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    copyloopvar:
      check-alias: true
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
    grouper:
      const-require-single-const: true
      const-require-grouping: true
      import-require-single-import: true
      import-require-grouping: false
      type-require-single-type: false
      type-require-grouping: false
      var-require-single-var: true
      var-require-grouping: false
    nolintlint:
      require-explanation: true
      require-specific: true
    unparam:
      check-exported: true
  exclusions:
    presets:
      - comments
      # - common-false-positives
      # - legacy
      # - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - revive
        path: 'util/*'
        text: 'var-naming: avoid meaningless package names'
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
