---
# The subdirectory functionality is not yet released; these files are
# provided as examples for the next version of this driver. This message
# will be removed at release time when we make this new release the default
apiVersion: v1
kind: PersistentVolume
metadata:
  # The name of the PV
  name: pv-lustre-subdir
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    # This field should be the true size of the Azure Lustre you want
    # to used. So that, k8s can allocate resources better.
    storage: 4Ti
  csi:
    driver: azurelustre.csi.azure.com
    volumeAttributes:
      # The file system name of the existing Lustre
      fs-name: ${EXISTING_LUSTRE_FS_NAME}
      # The IP address of the existing Lustre
      mgs-ip-address: ${EXISTING_LUSTRE_IP_ADDRESS}
      # The subdirectory to create and mount per pod (cannot use pvc / pv metadata in static volumes)
      sub-dir: "${pod.metadata.namespace}_${pod.metadata.name}"
      # Whether the created subdirectory should be retained or deleted at pod exit
      # This parameter is required if "sub-dir" is provided
      retain-sub-dir: "false"
    # Make sure this VolumeID is unique in the cluster
    volumeHandle: ${UNIQUE_IDENTIFIER_VOLUME_ID}
  # "Delete" is not supported in static provisioning PV
  mountOptions:
    - noatime
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
