---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # The name of the StorageClass.
  name: subdir.azurelustre.csi.azure.com
parameters:
  # The IP address of the existing Lustre
  mgs-ip-address: ${EXISTING_LUSTRE_IP_ADDRESS}
  # The subdirectory to create and mount per pod
  sub-dir: "${pvc.metadata.name}_${pod.metadata.name}"
provisioner: azurelustre.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - noatime
  - flock
