---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: azurelustre.csi.azure.com
  labels:
    app.kubernetes.io/name: azurelustre-csi-driver
    app.kubernetes.io/part-of: azurelustre-csi-driver
    app.kubernetes.io/version: v0.6.0
spec:
  fsGroupPolicy: File
  attachRequired: false
  podInfoOnMount: true
