---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-azurelustre-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: azurelustre-csi-driver
    app.kubernetes.io/part-of: azurelustre-csi-driver
    app.kubernetes.io/version: latest
    app: csi-azurelustre-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-azurelustre-controller
      app.kubernetes.io/component: controller
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: csi-azurelustre-controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: azurelustre-csi-driver
        app.kubernetes.io/part-of: azurelustre-csi-driver
        app.kubernetes.io/version: latest
    spec:
      serviceAccountName: csi-azurelustre-controller-sa
      nodeSelector:
        kubernetes.io/os: linux  # add "kubernetes.io/role: master" to run controller on master node
      priorityClassName: system-cluster-critical
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/controlplane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
                  - key: kubernetes.azure.com/cluster
                    operator: Exists
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: In
                    values:
                      - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - csi-azurelustre-controller
                topologyKey: topology.kubernetes.io/zone
              weight: 10
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - csi-azurelustre-controller
                topologyKey: kubernetes.io/hostname
              weight: 5
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: csi-provisioner
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner:v5.2.0
          args:
            - -v=2
            - --leader-election
            - --timeout=15m
            - --extra-create-metadata=true
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - name: liveness-probe
          image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.15.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=120s
            - --health-port=29762
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - name: azurelustre
          image: mcr.microsoft.com/oss/v2/kubernetes-csi/azurelustre-csi:latest-noble
          imagePullPolicy: Always
          args:
            - -v=5
            - --endpoint=$(CSI_ENDPOINT)
          ports:
            - containerPort: 29762
              name: healthz
              protocol: TCP
          # Reserved port for metrics
          # - containerPort: 29764
          #   name: metrics
          #   protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: AZURELUSTRE_CSI_ROLE
              value: controller
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: AZURE_TOKEN_CREDENTIALS
              value: ManagedIdentityCredential
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /etc/kubernetes/
              name: azure-cred
          resources:
            limits:
              cpu: 1
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: azure-cred
          hostPath:
            path: /etc/kubernetes/
            type: DirectoryOrCreate
