---
name: codespell
on:
  push:
    branches: [main, development, 'release/**']
  pull_request:
    branches: [main, development]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Enable codespell annotations
        run: echo "::add-matcher::.github/codespell-problem-matcher.json"
      - name: Run codespell
        run: hack/verify-codespell.sh
      - name: Disable codespell annotations
        if: always()
        run: |
          echo "::remove-matcher owner=codespell-matcher-default::"
          echo "::remove-matcher owner=codespell-matcher-specified::"
