---
name: Sanity Test Local

# Controls when the workflow will run
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Run-Sanity-Test-Local:
    name: Run Sanity Test Local
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Go 1.x
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version-file: 'go.mod'
        id: go
      - name: Run Sanity Test
        run: make sanity-test-local
